### ISSUE TITLE
[New Feature]: Adding Responsive Navbar and Footer

### ISSUE THREAD

**Issue by its-kumar-yash** [GameSphere-MultiPlayer/Dot-Box#13]
### 🎮 feature Request

I will add a responsive navbar and footer using HTML CSS

Kindly assign this to me

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by SrinivasDevolper** [comment]
this project please assign me

**Comment by kanikaa-3018** [comment]
please assign this issue to me for GSSoc'24. i can improve the navbar and even include hover effects

**Comment by Kash2612** [comment]
I want to work on this issue and add a responsive header and footer along with improving it's animation upon user hovering.
I have previously created websites with responsive navbars. Kindly assign this issue to me for GSSoC'24

**Comment by iamkanhaiyakumar** [comment]
I'm excited to contribute to the Adding Responsive Navbar and Footer . Could you please assign me.

**Comment by ishap11** [comment]
Hello. I'm eager to contribute to the Dot-Box project by adding a responsive navbar and footer. Could you please assign this task to me under GSSoC24.Thankyou!

**Comment by Durgesh4993** [comment]
@its-kumar-yash @kanikaa-3018 @iamkanhaiyakumar @SrinivasDevolper @ishap11 Please raise any other issue, because someone is already working on it

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
