### ISSUE TITLE
[New Feature]: To Restart The Game

### ISSUE THREAD

**Issue by anurag2787** [GameSphere-MultiPlayer/Dot-Box#25]
### 🎮 feature Request

WE Can reset the Game and Only Store the winning player details to display in Scoreboard 

### Point down the features

It will provide a user to easy to restart the game quickly without going back and Starting new game again 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by anurag2787** [comment]
Hello ,I would like to work on this issue please assign me
Under GSSoC24

**Comment by Lalita14ritgithub** [comment]
I would like to work on this issue please assign this task to me under GSSOC'24

**Comment by royalrajputayush** [comment]
I want to work on the nav section, please assign me this under gssoc level 2

Record
 I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue

**Comment by Abhay152002** [comment]
please add the label for gssoc'24 . 
i want to work on this issue, please assign it to me

**Comment by Durgesh4993** [comment]
@royalrajputayush @Abhay152002 @Lalita14ritgithub @anurag2787 Please raise any other issue, because someone is already working on this issue.

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
