### ISSUE TITLE
[New Feature]: Adding dark mode functionality 

### ISSUE THREAD

**Issue by rajlaxmi03** [GameSphere-MultiPlayer/Dot-Box#40]
### 🎮 feature Request

Adding dark mode functionality 

### Point down the features

feature points

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by harshita1611** [comment]
Hi, I would like to work on this issue, can you please assign it to me?

**Comment by royalrajputayush** [comment]
I want to work on the nav section, please assign me this under gssoc level 2

Record
 I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue

**Comment by Abhay152002** [comment]
I can work on this issue, please assign it to me under gssoc'24.

**Comment by Shubhra-Narang** [comment]
Kindly assign me this issue ,I can contribute to this

**Comment by Durgesh4993** [comment]
@harshita1611 @royalrajputayush @Abhay152002 @rajlaxmi03 @Shubhra-Narang  Please raise any other issue, because someone is already working on this issue.

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
